# Generated by Django 5.2.11 on 2026-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npm', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['npm'],
            },
        ),
    ]
