# Generated by Django 6.0.3 on 2026-04-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_session_version'),
        ('chat_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['owner', '-last_message_at', '-updated_at', '-created_at'], name='session_owner_recency_idx'),
        ),
    ]
