# Generated by Django 6.0.3 on 2026-04-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sessions', '0002_session_session_owner_recency_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='history_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='history_summary_watermark',
            field=models.IntegerField(default=0),
        ),
    ]
