# Generated by Django 6.0.3 on 2026-04-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_sessions", "0002_session_session_owner_recency_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at", "id"],
                name="chatmsg_sess_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedoutput",
            index=models.Index(
                fields=["session", "created_at", "id"],
                name="genout_sess_created_idx",
            ),
        ),
    ]
