# Generated by Django 6.0.3 on 2026-04-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sessions', '0003_chatmessage_generatedoutput_session_created_idx'),
        ('chat_sessions', '0003_session_history_summary_and_more'),
    ]

    operations = [
    ]
