# Generated by Django 6.0.3 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_sessions", "0004_merge_20260426_0831"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedoutput",
            name="export_output_json",
            field=models.JSONField(default=dict),
        ),
    ]
