# Generated by Django 6.0.3 on 2026-04-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sessions', '0005_generatedoutput_export_output_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedoutput',
            name='export_output_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
