# Generated by Django 6.0.3 on 2026-04-08 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('custom_name', models.CharField(blank=True, default='', max_length=255)),
                ('output_json', models.JSONField()),
                ('status_processing', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='artifact_histories', to='authentication.user')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
