# Generated by Django 6.0.3 on 2026-04-08 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_id', models.CharField(max_length=255, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('zip', 'ZIP'), ('xlsx', 'XLSX')], max_length=10)),
                ('status_processing', models.CharField(max_length=50)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='artifact_histories', to='authentication.user')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
