# Generated by Django 6.0.3 on 2026-04-10 14:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("artifact_history", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryExportArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("requested_format", models.CharField(choices=[("csv", "CSV"), ("xlsx", "XLSX")], max_length=10)),
                ("artifact_type", models.CharField(choices=[("csv", "CSV"), ("zip", "ZIP"), ("xlsx", "XLSX")], max_length=10)),
                ("file_id", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="export_artifacts", to="artifact_history.artifacthistory")),
                ("owner", models.ForeignKey(db_column="owner_id", on_delete=django.db.models.deletion.CASCADE, related_name="history_export_artifacts", to="authentication.user")),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("history", "owner", "requested_format"),
                        name="unique_history_export_artifact_per_format",
                    )
                ],
            },
        ),
    ]
