# Generated by Django 6.0.3 on 2026-05-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact_history', '0002_historyexportartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifacthistory',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
